"""Backup

Revision ID: 4262dfba730c
Revises: 0ee008bd320c
Create Date: 2026-01-22 11:16:48.887981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4262dfba730c'
down_revision = '0ee008bd320c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('size_mb', sa.Float(), nullable=True),
    sa.Column('tables_included', sa.Text(), nullable=True),
    sa.Column('backup_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backups')
    # ### end Alembic commands ###
