"""add_direccion_notificaciones

Revision ID: 9bda4c042c83
Revises: 1a656a492f82
Create Date: 2026-02-06 13:16:44.433715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bda4c042c83'
down_revision = '1a656a492f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_texto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('direccion_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pedido_json', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'direcciones', ['direccion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pedido_json')
        batch_op.drop_column('direccion_id')
        batch_op.drop_column('direccion_texto')

    # ### end Alembic commands ###
