"""add-target

Revision ID: 9e7a26a315a1
Revises: 9bda4c042c83
Create Date: 2026-02-10 15:09:24.388260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7a26a315a1'
down_revision = '9bda4c042c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('info_pago_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.drop_column('notas')
        batch_op.drop_column('info_pago_json')
        batch_op.drop_column('metodo_pago')

    # ### end Alembic commands ###
