"""add-code-backup-2

Revision ID: f98b9f2bda2b
Revises: 
Create Date: 2026-03-23 00:45:17.262051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98b9f2bda2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dietas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('objetivo', sa.String(length=50), nullable=False),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('calorias_diarias', sa.Integer(), nullable=False),
    sa.Column('nivel_actividad', sa.String(length=50), nullable=False),
    sa.Column('restricciones', sa.Text(), nullable=True),
    sa.Column('comidas_por_dia', sa.Integer(), nullable=False),
    sa.Column('plan_alimentacion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suplementos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('presentacion', sa.String(length=50), nullable=False),
    sa.Column('beneficios', sa.Text(), nullable=True),
    sa.Column('modo_uso', sa.Text(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('tipo_cuenta', sa.String(length=20), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('tutor_nombre', sa.String(length=100), nullable=True),
    sa.Column('tutor_telefono', sa.String(length=20), nullable=True),
    sa.Column('restricciones_infantiles', sa.Text(), nullable=True),
    sa.Column('backup_code', sa.String(length=50), nullable=True),
    sa.Column('backup_code_generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('dietas_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('dieta_base_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('perfil_usuario', sa.Text(), nullable=True),
    sa.Column('plan_generado', sa.Text(), nullable=False),
    sa.Column('progreso', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dieta_base_id'], ['dietas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=200), nullable=False),
    sa.Column('numero_exterior', sa.String(length=20), nullable=False),
    sa.Column('numero_interior', sa.String(length=20), nullable=True),
    sa.Column('colonia', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=False),
    sa.Column('referencias', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('predeterminada', sa.Boolean(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarjetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre_titular', sa.String(length=100), nullable=False),
    sa.Column('numero_tarjeta', sa.String(length=255), nullable=False),
    sa.Column('numero_enmascarado', sa.String(length=20), nullable=False),
    sa.Column('mes_expiracion', sa.String(length=2), nullable=False),
    sa.Column('anio_expiracion', sa.String(length=4), nullable=False),
    sa.Column('tipo_tarjeta', sa.String(length=20), nullable=False),
    sa.Column('predeterminada', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_unico', sa.String(length=10), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=False),
    sa.Column('telefono_usuario', sa.String(length=20), nullable=False),
    sa.Column('tipo_pedido', sa.String(length=20), nullable=False),
    sa.Column('suplemento_id', sa.Integer(), nullable=True),
    sa.Column('tarjeta_id', sa.Integer(), nullable=True),
    sa.Column('direccion_texto', sa.Text(), nullable=True),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=20), nullable=True),
    sa.Column('info_pago_json', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('pedido_json', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['direccion_id'], ['direcciones.id'], ),
    sa.ForeignKeyConstraint(['suplemento_id'], ['suplementos.id'], ),
    sa.ForeignKeyConstraint(['tarjeta_id'], ['tarjetas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_unico')
    )
    op.create_table('seguimiento_dieta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dieta_usuario_id', sa.Integer(), nullable=False),
    sa.Column('dia_numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('comidas_completadas', sa.Text(), nullable=True),
    sa.Column('calorias_consumidas', sa.Integer(), nullable=True),
    sa.Column('agua_consumida', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dieta_usuario_id'], ['dietas_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('datos_adicionales', sa.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_leida', sa.DateTime(), nullable=True),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    op.drop_table('seguimiento_dieta')
    op.drop_table('ordenes')
    op.drop_table('tarjetas')
    op.drop_table('direcciones')
    op.drop_table('dietas_usuario')
    op.drop_table('users')
    op.drop_table('suplementos')
    op.drop_table('dietas')
    # ### end Alembic commands ###
